apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: du53x5c3q-go
  janus-idp.io/tekton: du53x5c3q-go
  backstage.io/kubernetes-id: du53x5c3q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: du53x5c3q-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
